#!/bin/sh

# Enable on boot
/etc/init.d/wrtbwmon enable

# Configure our cron
if [ -d "/etc/crontabs" ]; then
  echo "PATH=/usr/sbin:/usr/bin:/sbin:/bin" > wrtbwmon
  echo "* * * * * /usr/sbin/wrtbwmon.sh update /tmp/usage.db" >> wrtbwmon
  echo "0 * * * * /usr/sbin/wrtbwmon.sh publish /tmp/usage.db /tmp/usage.htm" >> wrtbwmon
fi
/etc/init.d/cron reload

# Symlink to our webdir
if [ -d "/var/www/html" ]; then
  ln -s /tmp/usage.htm /www/usage.htm
elif [ -d "/www" ]; then
 ln -s /tmp/usage.htm /www/usage.htm
fi

exit 0
